apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default # Ensure this matches K8S_NAMESPACE or remove if namespace is in Jenkinsfile
  labels:
    app: nginx
spec:
  replicas: 2 # Adjust as needed
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine # Using a specific stable version is good practice
        ports:
        - containerPort: 80

